// Generated by gencpp from file beginner_tutorials/ROSDummyService.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ROSDUMMYSERVICE_H
#define BEGINNER_TUTORIALS_MESSAGE_ROSDUMMYSERVICE_H

#include <ros/service_traits.h>


#include <beginner_tutorials/ROSDummyServiceRequest.h>
#include <beginner_tutorials/ROSDummyServiceResponse.h>


namespace beginner_tutorials
{

struct ROSDummyService
{

typedef ROSDummyServiceRequest Request;
typedef ROSDummyServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ROSDummyService
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::ROSDummyService > {
  static const char* value()
  {
    return "750b33477ca2c16afaec99713dc8cb06";
  }

  static const char* value(const ::beginner_tutorials::ROSDummyService&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::ROSDummyService > {
  static const char* value()
  {
    return "beginner_tutorials/ROSDummyService";
  }

  static const char* value(const ::beginner_tutorials::ROSDummyService&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::ROSDummyServiceRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::ROSDummyService > 
template<>
struct MD5Sum< ::beginner_tutorials::ROSDummyServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::ROSDummyService >::value();
  }
  static const char* value(const ::beginner_tutorials::ROSDummyServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::ROSDummyServiceRequest> should match 
// service_traits::DataType< ::beginner_tutorials::ROSDummyService > 
template<>
struct DataType< ::beginner_tutorials::ROSDummyServiceRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::ROSDummyService >::value();
  }
  static const char* value(const ::beginner_tutorials::ROSDummyServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::ROSDummyServiceResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::ROSDummyService > 
template<>
struct MD5Sum< ::beginner_tutorials::ROSDummyServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::ROSDummyService >::value();
  }
  static const char* value(const ::beginner_tutorials::ROSDummyServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::ROSDummyServiceResponse> should match 
// service_traits::DataType< ::beginner_tutorials::ROSDummyService > 
template<>
struct DataType< ::beginner_tutorials::ROSDummyServiceResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::ROSDummyService >::value();
  }
  static const char* value(const ::beginner_tutorials::ROSDummyServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ROSDUMMYSERVICE_H
