// Generated by gencpp from file beginner_tutorials/ROSDummyServiceResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ROSDUMMYSERVICERESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_ROSDUMMYSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct ROSDummyServiceResponse_
{
  typedef ROSDummyServiceResponse_<ContainerAllocator> Type;

  ROSDummyServiceResponse_()
    : strOut()  {
    }
  ROSDummyServiceResponse_(const ContainerAllocator& _alloc)
    : strOut(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strOut_type;
  _strOut_type strOut;





  typedef boost::shared_ptr< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ROSDummyServiceResponse_

typedef ::beginner_tutorials::ROSDummyServiceResponse_<std::allocator<void> > ROSDummyServiceResponse;

typedef boost::shared_ptr< ::beginner_tutorials::ROSDummyServiceResponse > ROSDummyServiceResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::ROSDummyServiceResponse const> ROSDummyServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c74905a3ea523b8e617d78fc75224eb9";
  }

  static const char* value(const ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc74905a3ea523b8eULL;
  static const uint64_t static_value2 = 0x617d78fc75224eb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/ROSDummyServiceResponse";
  }

  static const char* value(const ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string strOut\n"
;
  }

  static const char* value(const ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.strOut);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROSDummyServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::ROSDummyServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "strOut: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strOut);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ROSDUMMYSERVICERESPONSE_H
