// Generated by gencpp from file beginner_tutorials/ROSDummyServiceRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ROSDUMMYSERVICEREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_ROSDUMMYSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct ROSDummyServiceRequest_
{
  typedef ROSDummyServiceRequest_<ContainerAllocator> Type;

  ROSDummyServiceRequest_()
    : strIn()  {
    }
  ROSDummyServiceRequest_(const ContainerAllocator& _alloc)
    : strIn(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strIn_type;
  _strIn_type strIn;





  typedef boost::shared_ptr< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ROSDummyServiceRequest_

typedef ::beginner_tutorials::ROSDummyServiceRequest_<std::allocator<void> > ROSDummyServiceRequest;

typedef boost::shared_ptr< ::beginner_tutorials::ROSDummyServiceRequest > ROSDummyServiceRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::ROSDummyServiceRequest const> ROSDummyServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a164d78cb7d5317e82d771dfd432287";
  }

  static const char* value(const ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a164d78cb7d5317ULL;
  static const uint64_t static_value2 = 0xe82d771dfd432287ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/ROSDummyServiceRequest";
  }

  static const char* value(const ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string strIn\n"
;
  }

  static const char* value(const ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.strIn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROSDummyServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::ROSDummyServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "strIn: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strIn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ROSDUMMYSERVICEREQUEST_H
